// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger Example

    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json
    - application/xml

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
