// Code generated by go-swagger; DO NOT EDIT.

package blacklist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddToBlackListMethodNotAllowedCode is the HTTP code returned for type AddToBlackListMethodNotAllowed
const AddToBlackListMethodNotAllowedCode int = 405

/*AddToBlackListMethodNotAllowed Invalid input

swagger:response addToBlackListMethodNotAllowed
*/
type AddToBlackListMethodNotAllowed struct {
}

// NewAddToBlackListMethodNotAllowed creates AddToBlackListMethodNotAllowed with default headers values
func NewAddToBlackListMethodNotAllowed() *AddToBlackListMethodNotAllowed {

	return &AddToBlackListMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddToBlackListMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
