// Code generated by go-swagger; DO NOT EDIT.

package blacklist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/AlexsJones/cloud-native-example/models"
)

// GetBlackListOKCode is the HTTP code returned for type GetBlackListOK
const GetBlackListOKCode int = 200

/*GetBlackListOK successful operation

swagger:response getBlackListOK
*/
type GetBlackListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Blacklist `json:"body,omitempty"`
}

// NewGetBlackListOK creates GetBlackListOK with default headers values
func NewGetBlackListOK() *GetBlackListOK {

	return &GetBlackListOK{}
}

// WithPayload adds the payload to the get black list o k response
func (o *GetBlackListOK) WithPayload(payload []*models.Blacklist) *GetBlackListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get black list o k response
func (o *GetBlackListOK) SetPayload(payload []*models.Blacklist) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlackListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Blacklist, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBlackListBadRequestCode is the HTTP code returned for type GetBlackListBadRequest
const GetBlackListBadRequestCode int = 400

/*GetBlackListBadRequest Invalid status value

swagger:response getBlackListBadRequest
*/
type GetBlackListBadRequest struct {
}

// NewGetBlackListBadRequest creates GetBlackListBadRequest with default headers values
func NewGetBlackListBadRequest() *GetBlackListBadRequest {

	return &GetBlackListBadRequest{}
}

// WriteResponse to the client
func (o *GetBlackListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
